### Login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
    "username": "admin_comson1",
    "password": "123456"
}

### Me
GET http://127.0.0.1:8000/api/auth/me
Authorization: Bearer dev-token-21128

### Logout
POST http://127.0.0.1:8000/api/auth/logout
Authorization: Bearer dev-token-20960

### Current Tracking
GET http://127.0.0.1:8000/api/tracking/current
Authorization: Bearer dev-token-15878



