### Login
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{
    "username": "mcap",
    "password": "1234"
}

### Me
GET http://127.0.0.1:8000/api/auth/me
Authorization: Bearer dev-token-16564

### Logout
POST http://127.0.0.1:8000/api/auth/logout
Authorization: Bearer dev-token-20960

### Current Tracking
GET http://127.0.0.1:8000/api/tracking/current
Authorization: Bearer dev-token-15878



