@host = http://127.0.0.1:8000
@token = RAuV8R7U4L1VVftJBTmfZJXk1idmRHhp4E3nymIOYNUwJuYdIS2W3qho4wOZVgRxIKuEafx6Ebvv95I2
@imei = 864606041741959
@dateFrom = 2026-06-01
@dateTo = 2026-06-01
@startTime = 00:00
@endTime= 23:59

### Mobile History - With Time
GET {{host}}/api/mobile/v1/tracking/history?imei={{imei}}&start_date={{dateFrom}}&end_date={{dateTo}}&start_time=00:00&end_time=23:59
Authorization: Bearer {{token}}
Accept: application/json


### Mobile History - Pagination
GET {{host}}/api/mobile/v1/tracking/history?imei={{imei}}&start_date={{dateFrom}}&end_date={{dateTo}}&start_time=00:00&end_time=23:59&page=1&per_page=1000
Authorization: Bearer {{token}}
Accept: application/json
